### PR TITLE
Stage 2

### PR DESCRIPTION
**Pull request by mistifikatorcat**

### CODE REVIEW

**Comment by FiLLa-FaS** [comment]
Hey! Thank you for sending your project for review, it looks very good! There're several issues, please fix them to pass this diploma stage. Good luck!✨

# Summary:
### Performance Criteria

- [x]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout and get out of the grid in the layout.
    * Popup mismatches: 
        - Incorrect font weight of the popup title
        - No labels for popup inputs https://skr.sh/sHStlaGo0wQ?a
        - Error message, submit button and switch link looks incorrectly
        - Popup window doesn't correspond the mockup on 320 and 768 viewports
    * Incorrect location of `header__logo` on 1440 and 768 viewports
    * Incorrect font weight of `searchResults__title`, `card__title` and `about__title`
    * Incorrect font of `footer__link`
    * Incorrect location of `about` on 1440 viewport https://skr.sh/sHSJ89oWxVH?a
    * Incorrect line-height of `searchForm__title` on 768 viewport
    * Incorrect location of `searchForm__wrapper` on 768 viewport https://skr.sh/sHSBdpwNbQq?a
    * Incorrect text properties of `searchResults__title` on 768, 320 viewport
    * There should be 3 cards in a row on 768 viewport
    * Incorrect height of the news card on 768 viewport
    * Incorrect size of `about__image` on 768 viewport
    * Incorrect distance between the footer and the end of the page on 768 viewport
    * Incorrect distance between search input and search button on 320 viewport
    * Incorrect width and height of news card on 320 viewport
    * `searchResults__more` text shouldn't wrap to another line on 320 viewport https://skr.sh/sHSrOZaSCpr?a
    * Incorrect width of `about__text-wrapper` on 320 viewport
    * Incorrect width of the footer and distance between footer links on 320 viewport
    * `searchForm` and `about` section should be centered horizontally on intermediate screen resolutions
    * Incorrect location of `mobile-menu__button` on 320 viewport
    * Incorrect text properties of `savedNewsHeader__label`
    * Incorrect location and width of `savedNewsHeader` and `grid` on 1440 viewport
    * Distance between saved cards and footer looks incorrectly (please check the background color here and in mockup https://skr.sh/sHSYGYGqyMP?a
    * `savedNewsHeader` is displayed incorrectly on 768 and 320 viewports, you need to set correct text properties for all elements and spaces between them in different screen resolutions according to the design page
- [x]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
    * Footer links should be opened in a new tab
    * I can't reach Sign Up popup because switch link in Sign In popup doesn't work correctly
    * You should add `saved-news` tab in the header navigation https://skr.sh/sHShMmrWWDy?a
- [x]  Classes are named according to BEM specifications.
    * You need to remove all capital letters from all class names throughout the project
    * Entity can't be block and element of this block at the same time https://skr.sh/sHS7Mk3NWGt?a
    * You need to use here key-value modifier instead of boolean https://skr.sh/sHSoiVN7eg8?a https://skr.sh/sHSGk6Taazb?a
    * You can't use BEM element outside of its block https://skr.sh/sHSC13pIJz5?a
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
    * You can't use two `h1` tags on the page https://skr.sh/sHS1TwcV0BC?a
    * Saved Articles page can't have `h1` tag at all
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [ ]  There are no linting errors or warnings.
    * https://skr.sh/sHSnFIPoOjs?a

### Best Practices

- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.
    * No active state for `searchForm__submit`
    * `card__button` hover should be an active state, and for hover you should use styles from mockup https://skr.sh/sHS1srSNGG9?a
    * Popup submit button looks incorrectly - it should have correct default, hover and disabled states
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
    * Not all fonts have alternatives https://skr.sh/sHSGFJtdP3G?a
- [x]  Images have an `alt` attribute containing appropriate values.
    * Not all images have `alt` sttribute
- [x]  Raster and vector images have been optimized.

## Number of points: 57

**Comment by mistifikatorcat** [comment]
Writing this for myself to not confuse myself on what I did and what I didn't:

- Fixed Navigation apart from the popups
- Fixed Incorrect font weight of searchResults__title, card__title and about__title
- Fixed Incorrect font of footer__link
- Fixed Incorrect location of about on 1440 viewport
- Fixed Incorrect location and width of savedNewsHeader and grid on 1440 viewport
- Removed h1 tag from about section

**Comment by mistifikatorcat** [comment]
- Fixed Incorrect line-height of searchForm__title on 768 viewport
- Fixed Incorrect location of searchForm__wrapper on 768 viewport 
- Fixed Incorrect text properties of searchResults__title on 768 viewport
- Fixed 3 cards in a row on 768 viewport
- Fixed Incorrect height of the news card on 768 viewport
- Fixed Incorrect size of about__image on 768 viewport
- Fixed Incorrect distance between the footer and the end of the page on 768 viewport
- Fixed Incorrect location of header__logo on 1440
- Fixed Incorrect distance between search input and search button on 320 viewport
- Fixed Incorrect width and height of news card on 320 viewport
- Fixed searchResults__more text shouldn't wrap to another line on 320 viewport https://skr.sh/sHSrOZaSCpr?a
- Fixed Incorrect width of about__text-wrapper on 320 viewport
- Fixed Incorrect width of the footer and distance between footer links on 320 viewport
- Fixed searchForm and about section should be centered horizontally on intermediate screen resolutions
- Fixed Incorrect location of mobile-menu__button on 320 viewport

**Comment by FiLLa-FaS** [comment]
Hey! Thanks for the corrections, your project has improved a lot since the last iteration. Btw there're still several issues in the code, and hope all comments will help you to create an amazing project and improve your skills. Good luck!✨

# Summary:
### Performance Criteria

- [x]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout and get out of the grid in the layout.
    * Incorrect text properties for `popup__redirect`
    * Popup window doesn't correspond the mockup on 320 and 768 viewports https://skr.sh/sHapwtcFlWQ?a https://skr.sh/sHal1cSZSaR?a
    * Incorrect location of `header__logo` on 768 viewport
    * Incorrect height of the `card` on 1440, 768, 320 viewports
    * Incorrect distance between the end of `search-form` and the end of `header` 768 viewport
    * Incorrect distance between `search-results__title` and `grid` on 768 viewport
    * Incorrect distance between `grid` and `search-results__more` on 768 viewport
    * Incorrect distance between `about` and `footer` on 768 viewport
    * No distance between footer and the end of the page on 768 viewport
    * Incorrect location of `mobile-menu__button` on 320 viewport https://skr.sh/sHaIlavDjlc?a
    * Incorrect height of `card__image` on 320 viewport
    * Incorrect location of card and `search-results__more` on 320 viewport https://skr.sh/sHagYVDRXMI?a https://skr.sh/sHacUC4iEGu?a
    * Content shouldnt' extend outside the parent container https://skr.sh/sHayRyLiGTr?a https://skr.sh/sHacBhrnS19?a https://skr.sh/sHaMYJpA0HG?a
    * Incorrect distance between the start of the `about` section and image inside the section on 320 viewport and between the image and the text inside the `about` section on 320 viewport https://skr.sh/sHaRLzsMh8Q?a 
    * Incorrect distance between `about` and `footer` on 320 viewport
    * `Roboto` font is not applied to `footer__link` (a typo in `font-family` style)
    * `saved-header` looks incorrectly on 768 and 320 viewport (you need to check all text properties and spaces between elements on these screen resolutions)
    * Incorrect width of `grid` on 768 viewport
- [x]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
    * The page scrolls horizontally on 320px - 336px for main page and on 320px - 336px, 541px - 602px
    * There shouldn't be two underlined styles in the header https://skr.sh/sHa4hIIcr87?a
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [x]  Classes are named according to BEM specifications.
    * It should be a BEM element instead of modifier https://skr.sh/sHa8v0bSo1C?a
    * Entity can't be block and element of this block at the same time https://skr.sh/sHaJNzFeLAA?a
    * You need to use here key-value modifier instead of boolean https://skr.sh/sHSoiVN7eg8?a https://skr.sh/sHSGk6Taazb?a
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
    * Saved Articles page can't have `h1` tag at all (h1 tag is placed only on the root page)
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.
    * https://skr.sh/sHSnFIPoOjs?a

### Best Practices

- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.
    * No active state for `search-form__submit`
    * `card__button` hover should be an active state, and for hover you should use styles from mockup https://skr.sh/sHS1srSNGG9?a
    * Popup submit button looks incorrectly - it should have correct default, hover and disabled states
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 60

**Comment by mistifikatorcat** [comment]
> Saved Articles page can't have h1 tag at all (h1 tag is placed only on the root page)

There isn't any (at least I don't see it)

**Comment by FiLLa-FaS** [comment]
I'm sorry for misunderstanding, I mean `saved-news` page doesn't have h1 tag at all, and `h1` tag should be on each page 🐸

**Comment by FiLLa-FaS** [comment]
Hey! Your project is almost finished, several small issues are left! Good luck 🙌

# Summary:
### Performance Criteria

- [x]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout and get out of the grid in the layout.
    * Popup window doesn't correspond the mockup on 320 and 768 viewports(https://skr.sh/sHcwJsvIibp?a vs https://skr.sh/sHcD3RVjz8P?a, https://skr.sh/sHcBogUhx9t?a vs https://skr.sh/sHc3837UWjM?a)
    * Incorrect height of the `card` on 1440, 768 viewports
    * Incorrect distance between footer and the end of the page on 768 viewport
    * Incorrect location of `mobile-menu__button` on 320 viewport https://skr.sh/sHaIlavDjlc?a
    * Text is located incorrectly in `search-results__more` on 320 viewport (it should be placed in one row)
- [x]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [x]  Classes are named according to BEM specifications.
    * You need to use here key-value modifier instead of boolean (https://skr.sh/sHcaEtKJrij?a examples on the screenshot, please fix all similar cases throughout the project). You can see difference between modifiers here https://en.bem.info/methodology/quick-start/#modifier
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [ ]  There are no linting errors or warnings.
    * https://skr.sh/sHc4YDPLwZN?a

### Best Practices

- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.
    * No active state for `search-form__submit`
    * `card__button` hover should be an active state, and for hover you should use styles from mockup https://skr.sh/sHS1srSNGG9?a
    * Popup submit button looks incorrectly - it should have correct default, hover and disabled states
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 77

**Comment by FiLLa-FaS** [comment]
Hey! You've got more than 80 points, so your project has been accepted! Btw you still can fix the rest issues below. Good luck on the next diploma stage!

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout and get out of the grid in the layout.
    * Incorrect width of the popup submit button on 768 viewport https://skr.sh/sHdWYHeXNJo?a
    * Incorrect height of the popup close button on 768 and 320 viewport https://skr.sh/sHdcsY1mDu3?a
    * Popup window shouldn't have space between the window and the end of the screen on 320 viewport https://skr.sh/sHddNi9A9C6?a
- [x]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [x]  Classes are named according to BEM specifications.
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.
    * No active state for `search-form__submit`
    * `card__button` hover should be an active state, and for hover you should use styles from mockup https://skr.sh/sHS1srSNGG9?a
    * Popup submit button looks incorrectly - it should have correct default, hover and disabled states
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 85

**Comment by mistifikatorcat** [comment]
>  There are no linting errors or warnings.

But I did fix those right before commit

image

**Comment by FiLLa-FaS** [comment]
Yep, my bad
I'll change the review in the post above and write correct diploma points. You can refer to this review in disputable situations. Good luck!

**Pull request merged**
